---
#  Copyright (c) 2018 Red Hat, Inc.
#
#  This file is part of ansible-tower-cicd.
#
#  ansible-tower-cicd is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ansible-tower-cicd is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ansible-tower-cicd.  If not, see <http://www.gnu.org/licenses/>.

# TODO: Make this task idempotent
- name: Ensure the extras repository is enabled
  become: yes
  command: yum-config-manager --enable extras
  when: ansible_os_family == 'RedHat'
  tags:
    - tower-install

- name: Download Tower setup
  get_url:
    url: "{{ tower_setup_release_url }}"
    dest: /var/tmp
  register: tower_download
  tags:
    - tower-install

- name: Extract Tower setup
  unarchive:
    src: "/var/tmp/{{ tower_setup_archive }}"
    dest: /var/tmp
    remote_src: yes
  when: tower_download is changed
  tags:
    - tower-install

- name: Create tower-setup configuration directory
  become: yes
  file:
    path: /etc/tower-setup
    state: directory
    owner: root
    group: root
    mode: 0700
  tags:
    - tower-install

- name: Create extra-vars file
  become: yes
  no_log: yes
  copy:
    content: "{{ tower_setup_config | to_nice_yaml }}"
    dest: /etc/tower-setup/extra-vars.yaml
    owner: root
    group: root
    mode: 0600
  tags:
    - tower-install

- name: Run Tower setup
  become: yes
  vars:
    setup: "/var/tmp/{{ tower_setup_basename }}-{{ tower_setup_version }}/setup.sh"
  command: "{{ setup }} -e @/etc/tower-setup/extra-vars.yaml"
  tags:
    - tower-install

- name: Wait for supervisor
  shell:
    executable: /bin/bash
    cmd: |
     set -o errexit -o pipefail
     supervisorctl status | awk '$2 != "RUNNING" { print $2 }'
  register: supervisorctl_status
  until: supervisorctl_status is success and supervisorctl_status.stdout == ''
  retries: 6

- name: Install ansible-tower-cli
  become: yes
  package:
    name: ansible-tower-cli
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('17.10', '>=')
  tags:
    - tower-cli
    - tower-post

- when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('17.10', '<')
  name: Install ansible-tower-cli using pip (distribution package not available)
  become: yes
  block:
    - name: Install pip
      vars:
        python_pkg_suffix: "{{ (ansible_python.version.major > 2) | ternary(ansible_python.version.major, '') }}"
      package:
        name: 'python{{ python_pkg_suffix }}-pip'
    - name: Install ansible-tower-cli
      pip:
        name: ansible-tower-cli
        state: present
  tags:
    - tower-cli
    - tower-post

# ini_file is used instead of ``tower-cli config`` because tower-cli doesn't
# accept blank (null) values for configuration options.
- name: Configure tower-cli
  become: yes
  ini_file:
    path: /etc/tower/tower_cli.cfg
    section: general
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    owner: root
    group: root
    mode: 0600
  with_dict: "{{ tower_setup_cli_config }}"
  tags:
    - tower-cli
    - tower-post

# TODO: Write a tower_license module
- name: Configure or update license
  no_log: yes
  vars:
    license: "{{ tower_setup_license | from_json }}"
  command: tower-cli setting modify -u '{{ tower_admin_username }}' -p '{{ tower_admin_password }}' LICENSE '{{ license | to_json }}'
  when: tower_setup_license_configure | bool
  tags:
    - tower-license
    - tower-post
