---
#  Copyright (c) 2018 Red Hat, Inc.
#
#  This file is part of ansible-tower-cicd.
#
#  ansible-tower-cicd is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ansible-tower-cicd is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ansible-tower-cicd.  If not, see <http://www.gnu.org/licenses/>.

tower_admin_username: admin
tower_admin_password: password
tower_setup_basename: ansible-tower-setup
tower_setup_version: 3.6.1-1
tower_setup_archive: "{{ tower_setup_basename }}-{{ tower_setup_version }}.tar.gz"
tower_setup_release_url: "https://releases.ansible.com/ansible-tower/setup/{{ tower_setup_archive }}"
tower_setup_config:
  create_preload_data: false
  admin_username: '{{ tower_admin_username }}'
  admin_password: '{{ tower_admin_password }}'
  nginx_http_port: "80"
  nginx_https_port: "443"
  pg_host: "127.0.0.1"
  pg_port: "5432"
  pg_database: tower
  pg_username: tower
  pg_password: password
  rabbitmq_port: "5672"
  rabbitmq_vhost: tower
  rabbitmq_username: tower
  rabbitmq_password: password
  rabbitmq_cookie: cookie
  # Needs to be true for fqdns and ip addresses
  rabbitmq_use_long_name: false

tower_setup_host: >-
  {% if tower_setup_config.nginx_disable_https|default(False) %}
  http://localhost
  {% else %}
  https://localhost
  {% endif %}

tower_setup_license_configure: false
# The literal license JSON, note that the "eula_accepted" key needs to be added manually.
tower_setup_license:
#  {
#    "company_name": "company_name",
#    "contact_email": "contact_email",
#    "contact_name": "contact_name",
#    "instance_count": 1,
#    "license_date": 1,
#    "license_key": "license_key",
#    "license_type": "enterprise",
#    "subscription_name": "subscription_name",
#    "trial": false,
#    "eula_accepted": true
#  }

tower_setup_cli_config:
  host: "{{ tower_setup_host }}"
  verify_ssl: false
  use_token: false
  verbose: false
  certificate:
  format: human
  color: true
  description_on:
  oauth_token:
